version: '3.1'
services:
    mysql:
        image: mysql:8.2
        container_name: mysqldb
        restart: always
        environment:
          MYSQL_DATABASE: facebook
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - .\data:/var/lib/mysql
        healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 3
    spring-app:
      build:
        dockerfile: Dockerfile
      container_name: facebook-app
      ports:
        - 11001:11001
      depends_on:
        mysql:
          condition: service_healthy
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/facebook
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_MINIO_URL=http://minio:9000
    minio:
        image: minio/minio
        container_name: minio
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        volumes:
            - .\minio:/data
            - .\minio\config:/root/.minio
        command: server --address 0.0.0.0:9000 --console-address ":9001" /data