version: '3.1'
services:
    mysql:
        image: mysql:latest
        container_name: mysqldb
        restart: always
        environment:
          MYSQL_DATABASE: facebook
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - .\data:/var/lib/mysql
        healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 3
    spring-app:
      build:
        dockerfile: Dockerfile
      container_name: facebook-app
      ports:
        - 11001:11001
      depends_on:
        mysql:
          condition: service_healthy
      environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/facebook
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root